### ISSUE TITLE
Shortcut project text does not update using VSCode Jellycut Support v1.0.1 plugin without restarting the bridge.

### ISSUE THREAD

**Issue by warthurton** [ActuallyZach/Jellycuts-Issues#90] opened 2021-05-19 16:48 UTC
## Describe the bug
Shortcut project text does not update using VSCode Jellycut Support v1.0.1 plugin without restarting the bridge.

## To Reproduce
1. Create .jelly in vscode
2. Open Jellycuts Bridge
3. Transfer file
4. Open file in Jellycuts
5. Make changes to .jelly in vscode and save
6. Transfer file
7. Yes to Replace Current Project
8. View project from Success
9. Text does not change
10. Close Jellycuts Bridge
11. Open Jellycuts Bridge
12. Transfer, Replace, View
13. Text has changed

## Expected behavior
If you save a new version of the .jelly file while the Jellycuts Bridge is running then transferring the file again should transfer the new saved version.

## Information
 - Device: iPhone 11 Pro
 - OS: iOS 14.5.1
 - Jullycuts v1.0(3)
 - Jailbroken? No
 - VS Code: Mac 1.56.2
 - Jellycut Support: v1.0.1

**Comment by ActuallyTaylor** [comment] 2021-05-20 20:51
This should be fixed in v1.0.2 of the Jellycuts bridge. Files will now update when they are saved in VSCode. If this works on your machine just reply and I can close the issue. Thank you!

**Comment by daneorie** [comment] 2021-05-23 03:21
I am also experiencing this issue of the file not being replaced. Using steps 10-12 does no even fix my issue. I found that I need to delete the file on my phone, completely close the Jellycuts app, reopen the app, and then transfer the file as if it were a new file completely. If I simply remove the file and transfer again (without restarting the app), the old version of the file somehow pops up again.

## Information
* Device: iPhone X
* OS: iOS 14.5.1
* Jellycuts: v1.0(3)
* Jailbroken? No
* VS Code: Mac 1.56.2
* Jellycuts Support: v1.0.3

**Comment by ActuallyTaylor** [comment] 2021-05-23 04:48
Strange, okay this seems to be an issue with the app saving files then. I will look into this for version 1.1

**Comment by warthurton** [comment] 2021-06-02 02:06
I see the update hit today. I will test here. Thanks for addressing.

**Comment by daneorie** [comment] 2021-06-02 03:52
Maybe I'm doing something incorrectly or my setup is wrong, but I can only "replace" an existing file by deleting it and then importing it from the bridge. If I keep the file and use the "Replace Current Project" option, nothing changes in the file on my device. This is still much better than before, where I had to both delete the file and quit Jellycuts completely, but it's not working as intended as far as I can tell.

### Information

- Device: iPhone X
- OS: iOS 14.6
- Jellycuts: v1.1(8)
- Jailbroken? No
- VS Code: Mac 1.56.2
- Jellycuts Support: v1.1.8?

**Comment by ActuallyTaylor** [comment] 2021-06-10 18:33
How is this in version 1.1.1?

**Comment by warthurton** [comment] 2021-06-10 18:41
Will check later today.

**Comment by ActuallyTaylor** [comment] 2022-05-25 03:57
Closing this issue because it has been almost a year. If it is reproducible in a current version it will be reopened.

**Closed as completed by ActuallyTaylor** 2022-05-25 03:57 UTC
Labels: bug
