### ISSUE TITLE
All my work was deleted

### ISSUE THREAD

**Issue by Yerbamatey** [ActuallyZach/Jellycuts-Issues#80] opened 2021-05-17 02:06 UTC
## Describe the bug
I was working on a shortcut and when I returned after a short break, all of my work was gone. Thankfully I didn’t do much before this happened.
## To Reproduce
Not sure

## Expected behavior
My work should be there when I return

### Screenshots
![503DF3B2-5117-48FF-98D4-E7112B96B1B8](https://user-images.githubusercontent.com/84298723/118423300-901c3d80-b679-11eb-85dd-4e44f44418e8.png)

## Information
 - Device: iPhone X
 - OS: iOS 14.5
 - Jellycuts Version v1.0(3)
 - Jailbroken? No

**Comment by ActuallyTaylor** [comment] 2021-05-17 02:13
That is very strange, I will check this out. Can you provide the code you had entered before leaving?

**Comment by ghost** [comment] 2021-06-19 18:10
This seems to just be a visual bug, there are no line numbers displayed.

**Comment by ActuallyTaylor** [comment] 2022-05-25 03:56
Closing this issue because it has been over a year and a lot has changed in the app. If it is still reproducible it will be reopened.

**Closed as completed** 2022-05-25 03:56 UTC
Labels: bug
